webtalk_init -webtalk_dir /home/bharathwaj/Research/fpgaStuff/xilinx/softwareDefinedRadio/WhiteShark/hdl/WaveformGenerators/triangle/syn/triangleZed/triangleZed.sim/sim_1/behav/xsim/xsim.dir/triangleZed_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sun Nov 17 11:16:22 2024" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2021.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3247384" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "20b47e22-bf75-49ab-87b6-62a2c79a27d2" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "7da736a225484a789bc709b6cf266162" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "22" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 24.04.1 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3798.352 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "25.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "51 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.03_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "116864_KB" -context "xsim\\usage"
webtalk_transmit -clientid 387664449 -regid "" -xml /home/bharathwaj/Research/fpgaStuff/xilinx/softwareDefinedRadio/WhiteShark/hdl/WaveformGenerators/triangle/syn/triangleZed/triangleZed.sim/sim_1/behav/xsim/xsim.dir/triangleZed_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/bharathwaj/Research/fpgaStuff/xilinx/softwareDefinedRadio/WhiteShark/hdl/WaveformGenerators/triangle/syn/triangleZed/triangleZed.sim/sim_1/behav/xsim/xsim.dir/triangleZed_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/bharathwaj/Research/fpgaStuff/xilinx/softwareDefinedRadio/WhiteShark/hdl/WaveformGenerators/triangle/syn/triangleZed/triangleZed.sim/sim_1/behav/xsim/xsim.dir/triangleZed_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
