#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2021.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Sun Nov 17 11:10:27 PST 2024
# SW Build 3247384 on Thu Jun 10 19:36:07 MDT 2021
#
# IP Build 3246043 on Fri Jun 11 00:30:35 MDT 2021
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim triangleZed_tb_behav -key {Behavioral:sim_1:Functional:triangleZed_tb} -tclbatch triangleZed_tb.tcl -view /home/bharathwaj/Research/fpgaStuff/xilinx/softwareDefinedRadio/WhiteShark/hdl/WaveformGenerators/triangle/sim/triangleZed_tb_behav.wcfg -log simulate.log"
xsim triangleZed_tb_behav -key {Behavioral:sim_1:Functional:triangleZed_tb} -tclbatch triangleZed_tb.tcl -view /home/bharathwaj/Research/fpgaStuff/xilinx/softwareDefinedRadio/WhiteShark/hdl/WaveformGenerators/triangle/sim/triangleZed_tb_behav.wcfg -log simulate.log

