# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/bharathwaj/Research/fpgaStuff/xilinx/openWifiPacketFilter/WhiteShark/fpga-drive-aximm-pcie/Vivado/pz_7z030_pcie/pz_7z030_pcie.srcs/sources_1/bd/pz_7z030_pcie/ip/pz_7z030_pcie_auto_pc_2/pz_7z030_pcie_auto_pc_2.xci
# IP: The module: 'pz_7z030_pcie_auto_pc_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/bharathwaj/Research/fpgaStuff/xilinx/openWifiPacketFilter/WhiteShark/fpga-drive-aximm-pcie/Vivado/pz_7z030_pcie/pz_7z030_pcie.gen/sources_1/bd/pz_7z030_pcie/ip/pz_7z030_pcie_auto_pc_2/pz_7z030_pcie_auto_pc_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pz_7z030_pcie_auto_pc_2'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/bharathwaj/Research/fpgaStuff/xilinx/openWifiPacketFilter/WhiteShark/fpga-drive-aximm-pcie/Vivado/pz_7z030_pcie/pz_7z030_pcie.srcs/sources_1/bd/pz_7z030_pcie/ip/pz_7z030_pcie_auto_pc_2/pz_7z030_pcie_auto_pc_2.xci
# IP: The module: 'pz_7z030_pcie_auto_pc_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/bharathwaj/Research/fpgaStuff/xilinx/openWifiPacketFilter/WhiteShark/fpga-drive-aximm-pcie/Vivado/pz_7z030_pcie/pz_7z030_pcie.gen/sources_1/bd/pz_7z030_pcie/ip/pz_7z030_pcie_auto_pc_2/pz_7z030_pcie_auto_pc_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pz_7z030_pcie_auto_pc_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
