# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/bharathwaj/Research/fpgaStuff/xilinx/openWifiPacketFilter/WhiteShark/fpga-drive-aximm-pcie/Vivado/src/constraints/pzfmc-7z015-7z030-1v8.xdc

# Block Designs: bd/pz_7z030_pcie/pz_7z030_pcie.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pz_7z030_pcie || ORIG_REF_NAME==pz_7z030_pcie} -quiet] -quiet

# IP: bd/pz_7z030_pcie/ip/pz_7z030_pcie_processing_system7_0_0/pz_7z030_pcie_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pz_7z030_pcie_processing_system7_0_0 || ORIG_REF_NAME==pz_7z030_pcie_processing_system7_0_0} -quiet] -quiet

# IP: bd/pz_7z030_pcie/ip/pz_7z030_pcie_axi_pcie_0_0/pz_7z030_pcie_axi_pcie_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pz_7z030_pcie_axi_pcie_0_0 || ORIG_REF_NAME==pz_7z030_pcie_axi_pcie_0_0} -quiet] -quiet

# IP: bd/pz_7z030_pcie/ip/pz_7z030_pcie_ref_clk_buf_0/pz_7z030_pcie_ref_clk_buf_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pz_7z030_pcie_ref_clk_buf_0 || ORIG_REF_NAME==pz_7z030_pcie_ref_clk_buf_0} -quiet] -quiet

# IP: bd/pz_7z030_pcie/ip/pz_7z030_pcie_xlconcat_0_0/pz_7z030_pcie_xlconcat_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pz_7z030_pcie_xlconcat_0_0 || ORIG_REF_NAME==pz_7z030_pcie_xlconcat_0_0} -quiet] -quiet

# IP: bd/pz_7z030_pcie/ip/pz_7z030_pcie_proc_sys_reset_0_0/pz_7z030_pcie_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pz_7z030_pcie_proc_sys_reset_0_0 || ORIG_REF_NAME==pz_7z030_pcie_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/pz_7z030_pcie/ip/pz_7z030_pcie_periph_intercon_0_0/pz_7z030_pcie_periph_intercon_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pz_7z030_pcie_periph_intercon_0_0 || ORIG_REF_NAME==pz_7z030_pcie_periph_intercon_0_0} -quiet] -quiet

# IP: bd/pz_7z030_pcie/ip/pz_7z030_pcie_periph_intercon_1_0/pz_7z030_pcie_periph_intercon_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pz_7z030_pcie_periph_intercon_1_0 || ORIG_REF_NAME==pz_7z030_pcie_periph_intercon_1_0} -quiet] -quiet

# IP: bd/pz_7z030_pcie/ip/pz_7z030_pcie_mem_intercon_0/pz_7z030_pcie_mem_intercon_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pz_7z030_pcie_mem_intercon_0 || ORIG_REF_NAME==pz_7z030_pcie_mem_intercon_0} -quiet] -quiet

# IP: bd/pz_7z030_pcie/ip/pz_7z030_pcie_rst_ps7_0_100M_0/pz_7z030_pcie_rst_ps7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pz_7z030_pcie_rst_ps7_0_100M_0 || ORIG_REF_NAME==pz_7z030_pcie_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/pz_7z030_pcie/ip/pz_7z030_pcie_auto_cc_0/pz_7z030_pcie_auto_cc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pz_7z030_pcie_auto_cc_0 || ORIG_REF_NAME==pz_7z030_pcie_auto_cc_0} -quiet] -quiet

# IP: bd/pz_7z030_pcie/ip/pz_7z030_pcie_auto_pc_0/pz_7z030_pcie_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pz_7z030_pcie_auto_pc_0 || ORIG_REF_NAME==pz_7z030_pcie_auto_pc_0} -quiet] -quiet

# IP: bd/pz_7z030_pcie/ip/pz_7z030_pcie_auto_pc_1/pz_7z030_pcie_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pz_7z030_pcie_auto_pc_1 || ORIG_REF_NAME==pz_7z030_pcie_auto_pc_1} -quiet] -quiet

# IP: bd/pz_7z030_pcie/ip/pz_7z030_pcie_auto_us_0/pz_7z030_pcie_auto_us_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pz_7z030_pcie_auto_us_0 || ORIG_REF_NAME==pz_7z030_pcie_auto_us_0} -quiet] -quiet

# IP: bd/pz_7z030_pcie/ip/pz_7z030_pcie_auto_cc_1/pz_7z030_pcie_auto_cc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pz_7z030_pcie_auto_cc_1 || ORIG_REF_NAME==pz_7z030_pcie_auto_cc_1} -quiet] -quiet

# IP: bd/pz_7z030_pcie/ip/pz_7z030_pcie_auto_cc_2/pz_7z030_pcie_auto_cc_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pz_7z030_pcie_auto_cc_2 || ORIG_REF_NAME==pz_7z030_pcie_auto_cc_2} -quiet] -quiet

# IP: bd/pz_7z030_pcie/ip/pz_7z030_pcie_auto_pc_2/pz_7z030_pcie_auto_pc_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pz_7z030_pcie_auto_pc_2 || ORIG_REF_NAME==pz_7z030_pcie_auto_pc_2} -quiet] -quiet

# XDC: /home/bharathwaj/Research/fpgaStuff/xilinx/openWifiPacketFilter/WhiteShark/fpga-drive-aximm-pcie/Vivado/pz_7z030_pcie/pz_7z030_pcie.gen/sources_1/bd/pz_7z030_pcie/pz_7z030_pcie_ooc.xdc
